"""Create payments and outbox tables

Revision ID: f5500c95bb2f
Revises: 
Create Date: 2026-08-03 18:29:01.730145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5500c95bb2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('PAYMENT_CREATED', 'PAYMENT_PROCESSED', name='event_type_enum'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_aggregate_id', 'outbox', ['aggregate_id'], unique=False)
    op.create_index('idx_outbox_status_created', 'outbox', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_aggregate_id'), 'outbox', ['aggregate_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency_enum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('payload_meta', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    op.create_index('idx_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index('idx_payments_status_created', table_name='payments')
    op.drop_index('idx_payments_idempotency_key', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_outbox_aggregate_id'), table_name='outbox')
    op.drop_index('idx_outbox_status_created', table_name='outbox')
    op.drop_index('idx_outbox_aggregate_id', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
